### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by ZFTurbo** [RetroCirce/Zero_Shot_Audio_Source_Separation#12]
Unfortunately I wasn't able to get close to paper results. My results on MUSDB18HQ dataset are following:
```
SDR bass: 1.0778
SDR drums: 2.5914
SDR other: 0.6353
SDR vocals: 2.9829
```

My method - I used as query 100 train tracks from MUSDB18HQ dataset. Then I created averaged 2048-vector for ['bass', 'drums', 'other' and 'vocals']. Then I split test tracks using this vector and calculated the SDR value. May be I missing something?

**Comment by RetroCirce** [comment]
For these results, I think there must be some errors. I have several suggestions/questions to see if you could find some problems:
1. Our checkpoint contains two parts: the first one is the separation model (zsp_full.ckpt), another is the htsat/st-sed detection system checkpoint (2048-d.ckpt). The sound event detection system's config file is htsat_config.py, did you also load this checkpoint in htsat_config.py?
2. if you download the musdb18 dataset from the official website, make sure it is converted to 32000 sample rate, because the original one is 44100.  You can also use our processed file, detail link in readme.md.
3. The query is from musdb18 training set, but it is the 30s highlight version and it does not contain the silence frame.  The testing set is the full testing set (i.e. not 30s). You can follow our readme.md link to find the highlight version, or you can extract it through the toolkit from sisec 2018.
4. Did you output some separation files to see how it separates? This number seems that it does not perform the separation.

**Comment by RetroCirce** [comment]
Also, if you do not use the highlight version of training set, it will also produce the similar result but slightly lower than the paper result (because some silence frames drop the embedding from a better one). But it should not be 0-3 SDR.

**Comment by ZFTurbo** [comment]
Yes probably problem was with sample rate. I changed it in config from 32000 to 44100. 
After our discussion I returned it back to 32000. My validation on MUSDB18HQ for bass increased from `1.0778` to `2.6361`. But it's still far from 3.8. I'm trying to find what else I'm missing.

I split your code for inference in 2 parts (I createed the pull request with these files):
1) `zero_shot_create_vector.py` - create vector out of queries
2) `zero_shot_process_file.py` - process file with vector

May be you can just post your vectors which you obtained for MUSDB dataset?

**Comment by RetroCirce** [comment]
Thank you for your commit, I will take a look and merge your commit. 
I have further suggestions regarding your reproduction:
1. The config.py and htsat_config.py files have the sample rate and you change it to 32000. **It is only responsible for how model loads the data.** Our model is trained on 32000Hz (AudioSet is 32000Hz) so you need to set it 32000Hz.
2. You also need to **convert the musdb18 dataset to 32000Hz** using librosa.resample, the original one is 44100Hz, changing the sample rate variable in configuration files do not automatically change the data input sample rate. Check out code **process_musdb in main.py** to see more details. You can use our processed 32000Hz files musdb-32000.npy in readme.md
3. When calculating SDR values, we use **the median SDR** not average SDR. This follows the SiSec 2018 and other music source separation evaluation, which is different from speech source separation (use average SDR more).

I attach my query on vocal, drum, bass, other below. This model can perform the SDRs below (one of our attempts, we have three attempts to get the average values in the paper):
[average_query_musdb.zip](https://github.com/RetroCirce/Zero_Shot_Audio_Source_Separation/files/8200611/average_query_musdb.zip)

![image](https://user-images.githubusercontent.com/22312598/157113664-510850aa-2f25-4682-9033-2694617cb3d6.png)

Please let me know if you have further questions, I'm happy to help you achieve the results I got.
