### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by Satisfy256** [RetroCirce/Zero_Shot_Audio_Source_Separation#14]
Hi.
I encountered problems when installing, there might be issues with the requirements.txt.
I ran pip install -r requirements.txt on a conda environment and then got an error about user requesting numpy 1.22.0. 
Numba 0.55.1, which is in the requirements, doesn't support 1.22.0.
So I installed numpy 1.21.5. When running main.py I got omegaconf error about unsupported value type.
Then I did pip install omegaconf -U and pip install hydra-core --upgrade and that fixed the issue.
I've been enjoying the program so far. The inferencing runs well on my cpu and I am able to do things that I wasn't able to with other source separation algorithms.

**Comment by RetroCirce** [comment]
Hi, thank you for your recognition on my work! And sorry for the requirement part because I just used the pyreq to generate the requirement txt, maybe there is a problem on it.

Based on your fixing process, if I understand correctly, I need to update the numba to be a higher version? Would you mind pulling a request in the "pull request" page to indicate a new requirement.txt? This will be more helpful

Thanks!!

best,
Ke
