### ISSUE TITLE
Export pred_.wav to stereo 

### ISSUE THREAD

**Issue by lucasbr15** [RetroCirce/Zero_Shot_Audio_Source_Separation#9]
Hello how are you? I'm really enjoying Zero Shot ASS,

I noticed that the files exported after the inference, are in WAV Mono format,

So my question is, would it be possible to somehow export the final result in stereo (2 channels)? If so, I imagine I should modify some lines in the config.py file, no?

Thanks again.

**Comment by RetroCirce** [comment]
Sorry, our model is settled on the mono waveform (1 channel) since the AudioSet training data is 1 channel. Many Separation models are targeted on the mono waveform. 

If you want to make it stereo, the only thing you can do is to copy the one channel to two channels, this can be done by writing another independent code to process the mono waveform, though it does not truly improve the quality.

Also, the mono waveform does not indicate the low quality, many recordings and samples need to be mono with high quality to help reduce the workload and make the pipeline consistent with other formats of audios.
